theme: jekyll-theme-minimal
title: Brigitte Gagné’s technical writing portfolio
description: An accomplished professional with 20+ years in the technology industry including 7 years as a technical writer.
